"""Initial schema

Revision ID: 11589ab0e946
Revises: 
Create Date: 2026-07-19 14:21:27.706704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11589ab0e946'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('hsn', sa.String(), nullable=True),
    sa.Column('gst_percent', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('blocked', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('routing_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_index(op.f('ix_vendors_tax_id'), 'vendors', ['tax_id'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('po_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('tolerance_percent', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('fulfilled_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('matched_po_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('pdf_storage_path', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('email_message_id', sa.String(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('matching_confidence', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('raw_extracted_data', sa.JSON(), nullable=True),
    sa.Column('field_confidences', sa.JSON(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('ocr_bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_explanation', sa.Text(), nullable=True),
    sa.Column('decision_evidence', sa.JSON(), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_decision'), 'invoices', ['decision'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tracking_id'), 'invoices', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('po_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('gst_percent', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['po_number'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_line_items_po_number'), 'po_line_items', ['po_number'], unique=False)
    op.create_index(op.f('ix_po_line_items_sku'), 'po_line_items', ['sku'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gr_number', sa.String(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['po_number'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_gr_number'), 'goods_receipts', ['gr_number'], unique=True)
    op.create_index(op.f('ix_goods_receipts_po_number'), 'goods_receipts', ['po_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goods_receipts_po_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_gr_number'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_po_line_items_sku'), table_name='po_line_items')
    op.drop_index(op.f('ix_po_line_items_po_number'), table_name='po_line_items')
    op.drop_table('po_line_items')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tracking_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_decision'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_vendors_tax_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
