"""Add invoice fields

Revision ID: 651afaf5e185
Revises: eb4f3f320c0e
Create Date: 2026-07-20 01:13:36.321360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651afaf5e185'
down_revision: Union[str, Sequence[str], None] = 'eb4f3f320c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('document_type', sa.String(), nullable=False, server_default='invoice'))
    op.add_column('invoices', sa.Column('sender_email', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('decided_by_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_file_hash'), 'invoices', ['file_hash'], unique=False)
    op.create_foreign_key(None, 'invoices', 'users', ['decided_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_file_hash'), table_name='invoices')
    op.drop_column('invoices', 'decided_by_user_id')
    op.drop_column('invoices', 'sender_email')
    op.drop_column('invoices', 'document_type')
    op.drop_column('invoices', 'file_hash')
    # ### end Alembic commands ###
