"""Add assignee_id and tags to invoice

Revision ID: eb4f3f320c0e
Revises: 434251c04054
Create Date: 2026-07-19 16:50:27.358936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4f3f320c0e'
down_revision: Union[str, Sequence[str], None] = '434251c04054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('assignee_id', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'tags')
    op.drop_column('invoices', 'assignee_id')
    # ### end Alembic commands ###
